### ISSUE TITLE
Carnet on Android claims newer nextcloud version needed when most current version is installed

### ISSUE THREAD

**Issue by menelic** [PhieF/CarnetDocumentation#29] opened 2019-02-12 16:17 UTC
Car etc is shaping up as a great keep alternative. Unfortunately on Android it prompts me to update the nextcloud app version to allow credentials-free nextcloud sync. But even after the update has been triggered through carnet and Nextcloud is current, it does not work. It still asks for "a newer nextcloud version" which does not exist... please fix so I can sync

**Comment by PhieF** [comment] 2019-02-12 17:58
Well that's because it is making for the next version of the nextcloud app, which is not released yet... Have you tried the other login option ?

**Comment by menelic** [comment] 2019-02-12 20:51
Yes I have, unfortunately it does not work either way

**Comment by menelic** [comment] 2019-02-15 09:10
with the latest nextcloud android update, the correct prefilled nextcloud account info appoears in carnet when I select sync with cloud > other options > connect with nextcloud > connect with the nextcloud app. After selecting the correct account (my android app connects to two accounts)  I get a "nextcloud has stoped message every time, sync still does not work. 

This happened whether or not I have the nextcloud app open.

Nextcloud account picking works on my hone eg in Davdroid so I  suspect it is a carnet issue

**Comment by PhieF** [comment] 2019-02-15 09:51
Hm I can't reproduce the issue, do you have adb on your computer ? What operating system do you use on your computer ?

Thanks

**Comment by jellykells** [comment] 2019-02-16 07:13
I'm experiencing the same issue with Carnet causing the Nextcloud app to crash as described by @menelic.
I do have adb installed on my PC running Windows 7.

**Comment by PhieF** [comment] 2019-02-16 10:02
Can you run adb logcat while the nextcloud app crashes (when it happens) and send me the result ?

**Comment by jellykells** [comment] 2019-02-16 16:53
@PhieF I'm seeing this whenever the Nextcloud app crashes.
>02-16 10:49:14.580  8595  8595 E AndroidRuntime: FATAL EXCEPTION: main
02-16 10:49:14.580  8595  8595 E AndroidRuntime: Process: com.nextcloud.client, PID: 8595
02-16 10:49:14.580  8595  8595 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.client/com.owncloud.android.ui.activity.SsoGrantPermissionActivity}: java.lang.NullPointerException:
Attempt to read from field 'java.lang.String android.accounts.Account.name' on a null object reference
02-16 10:49:14.580  8595  8595 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2750)
02-16 10:49:14.580  8595  8595 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2811)
02-16 10:49:14.580  8595  8595 E AndroidRuntime:        at android.app.ActivityThread.-wrap12(ActivityThread.java)
02-16 10:49:14.580  8595  8595 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528)
02-16 10:49:14.580  8595  8595 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
02-16 10:49:14.580  8595  8595 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
02-16 10:49:14.580  8595  8595 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6316)
02-16 10:49:14.580  8595  8595 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-16 10:49:14.580  8595  8595 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
02-16 10:49:14.580  8595  8595 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
02-16 10:49:14.580  8595  8595 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.String android.accounts.Account.name' on a null object reference
02-16 10:49:14.580  8595  8595 E AndroidRuntime:        at com.owncloud.android.ui.activity.SsoGrantPermissionActivity.onCreate(SsoGrantPermissionActivity.java:106)
02-16 10:49:14.580  8595  8595 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:6757)
02-16 10:49:14.580  8595  8595 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
02-16 10:49:14.580  8595  8595 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2703)
02-16 10:49:14.580  8595  8595 E AndroidRuntime:        ... 9 more`

**Comment by PhieF** [comment] 2019-02-17 17:22
OK,

just to be sure, you have both the lastest nextcloud app (fdroid or play store ?) and the latest carnet ?
Can are able to select the nextcloud account, then it crashed ?

Which android version are you using ? 

Thanks
This is I confess very weird

**Comment by jellykells** [comment] 2019-02-17 21:10
I'm using Nextcloud version 3.5.0 from the Play Store, and Carnet version 0.12.7 from F-Droid. I'm also using Android 7.0.

The crash occurs as soon as I tap "OK" after selecting my Nextcloud account in the pop-up dialog box.

**Comment by PhieF** [comment] 2019-02-18 09:59
Good news, I guess I've fixed it

can you try this apk ?

https://cloud.exode.me/index.php/s/bzaRk2nW2td426o

It was with android 7 only, thanks for helping me with this

**Comment by jellykells** [comment] 2019-02-20 12:03
Hm. Android installer doesn't like that APK.
![screenshot_2019-02-20-05-37-45](https://user-images.githubusercontent.com/42573508/53090479-2da55880-34d5-11e9-8c0c-13fce82b1ea2.png)

**Comment by PhieF** [comment] 2019-03-10 09:40
Hi, it should be fixed on current version ! Have you tried it ? Thanks !

**Closed by PhieF** 2019-03-10 09:40 UTC
